import json
import csv
import time
import argparse
import os
import itertools
from concurrent.futures import ProcessPoolExecutor
from collections import defaultdict
from tqdm import tqdm

# Import your existing logic
from utils.data_loader import load_game_data
from utils.constants import OPTIMAZATION_TARGET, GATHERING_SKILLS, ARTISAN_SKILLS, UTILITY_SKILLS
from models import CraftingNode, GearSet, Container
from drop_calculator import DropCalculator
from gear_optimizer import GearOptimizer
from calculations import calculate_passive_stats, _calculate_single_target_score
from ui_sidebar import extract_user_pets

# ONLY rely on the UI's native methods
from ui_utils import (
    build_activity_context, 
    get_compatible_services, 
    synthesize_activity_from_recipe, 
    get_best_auto_pet,
    extract_modifier_stats,
    extract_user_counts,
    get_user_collectibles,
    calculate_level_from_xp,
    extract_user_reputation,
    calculate_char_level_from_steps,
    calculate_total_level,
    is_material_level_valid
)

def load_all_game_data():
    base_path = "game_data/wiki_export/autogenerated"
    # The UI loads 7 main files via ui_utils
    items, activities, recipes, locations, services, collectibles, materials = load_game_data(
        f"{base_path}/equipment.json", f"{base_path}/activities.json",
        f"{base_path}/recipes.json", f"{base_path}/locations.json",
        f"{base_path}/services.json", f"{base_path}/collectibles.json",
        f"{base_path}/materials.json"
    )
    return items, activities, recipes, locations, services, collectibles, materials

def worker_init(user_state_dict):
    global items, activities, recipes, locations, services, collectibles, materials, drop_calc, pets, optimizer_pool, user_state
    
    items, activities, recipes, locations, services, collectibles, materials = load_all_game_data()
    
    # Initialize Drop Calculator & Optimizer
    drop_calc = DropCalculator()
    optimizer_pool = GearOptimizer(items, locations)
    
    # Load Pets
    pets = []
    try:
        from models import Pet
        pets_path = "game_data/wiki_export/autogenerated/pets.json"
        if os.path.exists(pets_path):
            with open(pets_path, "r", encoding="utf-8") as f:
                for p_data in json.load(f): pets.append(Pet(**p_data))
    except Exception as e:
        print(f"Failed to load pets: {e}")
        
    user_state = user_state_dict

def process_job(job):
    run_name = job['run_name']
    target_list = job['targets']
    obj_type = job['type']
    obj_id = job['id']
    is_fine = job['is_fine']
    service_id = job['service_id']
    location_id = job['location_id']
    selected_input_ids = job.get('selected_inputs', [])
    
    # Load all user stats EXACTLY as UI does
    user_ap = user_state.get('user_ap', 0)
    user_total_level = user_state.get('user_total_level', 0)
    user_reputation = user_state.get('user_reputation', {})
    player_char_lvl = user_state.get('calculated_char_lvl', 99)
    owned_item_counts = user_state.get('owned_item_counts', None)
    owned_collectibles = user_state.get('owned_collectibles', collectibles)
    skill_group_levels = user_state.get('skill_group_levels', {})
    owned_pets = user_state.get('owned_pets', {})
    
    extra_passive_stats = {}
    selected_input_materials = []

# 1. Resolve Raw Activity/Recipe
    if obj_type == "recipe":
        base_obj = next((r for r in recipes if r.id == obj_id), None)
        srv = next((s for s in services if s.id == service_id), None) if service_id else None
        
        if srv:
            final_activity = synthesize_activity_from_recipe(base_obj, srv)
            location_id = srv.location
            if srv.modifiers:
                extra_passive_stats = extract_modifier_stats(srv.modifiers)
        else:
            class WrappedRecipe:
                def __init__(self, r):
                    self.id = r.id
                    self.name = r.name
                    self.primary_skill = r.skill
                    self.level = r.level
                    self.base_xp = r.base_xp
                    self.base_steps = r.base_steps
                    self.max_efficiency = r.max_efficiency
                    self.locations = []
                    self.requirements = []
                    self.materials = r.materials
                    self.output_item_id = r.output_item_id
                    self.output_quantity = r.output_quantity

            final_activity = WrappedRecipe(base_obj)
            # location_id remains whatever was passed in the job (usually None for recipes without services)
            
    else:
        final_activity = next((a for a in activities if a.id == obj_id), None)

    if not final_activity: return None

    activity_skill = getattr(final_activity, 'skill', getattr(final_activity, 'primary_skill', '')).lower()
    player_skill_lvl = user_state.get("skill_levels", {}).get(activity_skill, 99)

    # 2. Resolve Input Materials (For Activities)
    for mat_id in selected_input_ids:
        mat_obj = next((m for m in materials if m.id == mat_id), None)
        if mat_obj:
            selected_input_materials.append(mat_obj)
            if mat_obj.modifiers:
                mat_stats = extract_modifier_stats(mat_obj.modifiers)
                for k, v in mat_stats.items():
                    extra_passive_stats[k] = extra_passive_stats.get(k, 0.0) + v

    # 3. Calculate input cost natively
    is_equipment_upgrade = False
    base_input_cost = 0.0
    
    if obj_type == "recipe" and getattr(final_activity, 'materials', None):
        for mat_group in final_activity.materials:
            mat_id = mat_group[0].item_id
            base_id = mat_id.replace("_fine", "")
            has_fine_version = base_id in drop_calc.fine_material_map
            
            actual_id = f"{base_id}_fine" if (is_fine and has_fine_version) else base_id
            base_input_cost += mat_group[0].amount * drop_calc.item_values.get(actual_id, 0.0)
            
            if not has_fine_version:
                is_equipment_upgrade = True
                
    elif obj_type == "activity" and getattr(final_activity, 'requirements', None):
        input_reqs = [r for r in final_activity.requirements if getattr(r.type, 'value', r.type) in ('keyword_count', 'input_keyword', 'item')]
        for i, req in enumerate(input_reqs):
            if i < len(selected_input_materials):
                mat = selected_input_materials[i]
                base_input_cost += req.value * drop_calc.item_values.get(mat.id, 0.0)

    # 4. Context setup
    loc_map = {loc.id: loc for loc in locations}
    context = build_activity_context(
        activity=final_activity, user_ap=user_ap, user_total_level=user_total_level,
        loc_map=loc_map, drop_calc=drop_calc, selected_location_id=location_id,
        skill_group_levels=skill_group_levels
    )
    
    # 5. SUBTRACT Fulfilled Material Keywords from Context
    req_kw = context.get("required_keywords", {})
    for mat in selected_input_materials:
        if hasattr(mat, 'keywords') and mat.keywords:
            for kw in mat.keywords:
                norm_kw = kw.lower().replace("_", " ").strip()
                req_kw.pop(norm_kw, None)
    context["required_keywords"] = req_kw
    
    context["is_fine_materials"] = is_fine
    context["is_equipment_upgrade"] = is_equipment_upgrade 
    context["base_input_cost"] = base_input_cost            
    context["drop_calc"] = drop_calc                  

    # 6. Auto-select Pet (Strict Ownership applied here)
    game_data_dict = {'recipes': {r.id: r for r in recipes}, 'activities': {a.id: a for a in activities}, 'pets': {p.id: p for p in pets}}
    dummy_node = CraftingNode(node_id="dummy", item_id="dummy", source_type=obj_type, source_id=obj_id, selected_location_id=location_id)
    best_pet_id, best_pet_lvl = get_best_auto_pet(
        dummy_node, game_data_dict, loc_map, drop_calc, 
        user_ap, user_total_level, use_owned=True, owned_pets=owned_pets
    )
    
    actual_pet = None
    if best_pet_id:
        p = next((p for p in pets if p.id == best_pet_id), None)
        if p: actual_pet = p.model_copy(update={"active_level": best_pet_lvl, "use_pet_ability": True})

    # 7. Run Optimization
    best_gear, error, _ = optimizer_pool.optimize(
        activity=final_activity, 
        player_level=player_char_lvl, 
        player_skill_level=player_skill_lvl,
        optimazation_target=target_list, 
        owned_item_counts=owned_item_counts,
        achievement_points=user_ap, 
        user_reputation=user_reputation, 
        owned_collectibles=owned_collectibles,
        extra_passive_stats=extra_passive_stats, 
        context_override=context, 
        pet=actual_pet, 
        consumable=None, # Ignoring Consumables per user request
        locked_items={}, # Ignoring Locks
        blacklisted_ids=set() # Ignoring Blacklists
    )

    if error or not best_gear:
        return None

    # Calculate final stats
    passive_stats = calculate_passive_stats(owned_collectibles, context)
    final_stats = best_gear.get_stats(context)
    for k, v in passive_stats.items(): final_stats[k] = final_stats.get(k, 0.0) + v
    for k, v in extra_passive_stats.items(): final_stats[k] = final_stats.get(k, 0.0) + v 

    # Extract Metrics
    xp_per_step = _calculate_single_target_score(OPTIMAZATION_TARGET.xp, final_activity, player_skill_lvl, final_stats, context)
    net_profit = _calculate_single_target_score(OPTIMAZATION_TARGET.net_profit_per_step, final_activity, player_skill_lvl, final_stats, context)
    out_in_ratio = _calculate_single_target_score(OPTIMAZATION_TARGET.materials_from_input, final_activity, player_skill_lvl, final_stats, context)
    steps_per_action = _calculate_single_target_score(OPTIMAZATION_TARGET.reward_rolls, final_activity, player_skill_lvl, final_stats, context)
    
    actual_steps = 1.0 / steps_per_action if steps_per_action > 0 else 0
    level_diff = max(0, player_skill_lvl - getattr(final_activity, 'level', 1))
    base_we = min(0.25, level_diff * 0.0125)
    total_we_percent = (final_stats.get('work_efficiency', 0) + base_we) * 100

    input_names = " + ".join([m.name for m in selected_input_materials]) if selected_input_materials else "None"

    row = {
        "Run Target": run_name,
        "Name": final_activity.name,
        "Type": obj_type.title(),
        "Skill": activity_skill.title(),
        "XP/Step": round(xp_per_step, 4),
        "Coins/1k Steps": round(net_profit * 1000, 2),
        "Output/Input Ratio": round(out_in_ratio, 4),
        "Location": location_id if location_id else "Any",
        "Inputs": input_names,
        "Variant Logic": "Fine" if is_fine else "Normal",
        "Pet": f"{actual_pet.name} (Lvl {actual_pet.active_level})" if actual_pet else "None",
        "Tools": " | ".join([t.name for t in best_gear.tools]),
        "Rings": " | ".join([r.name for r in best_gear.rings]),
        "Head": best_gear.head.name if best_gear.head else "",
        "Chest": best_gear.chest.name if best_gear.chest else "",
        "Legs": best_gear.legs.name if best_gear.legs else "",
        "Primary": best_gear.primary.name if best_gear.primary else "",
        "Secondary": best_gear.secondary.name if best_gear.secondary else "",
        "Base Steps": getattr(final_activity, 'base_steps', 0),
        "Final Steps/Action": round(actual_steps, 2),
        
        "Work Efficiency %": round(total_we_percent, 2),
        "Double Action %": round(final_stats.get('double_action', 0) * 100, 2),
        "Double Rewards %": round(final_stats.get('double_rewards', 0) * 100, 2),
        "No Mats Consumed %": round(final_stats.get('no_materials_consumed', 0) * 100, 2),
        "Quality Outcome": round(final_stats.get('quality_outcome', 0), 2),
    }
    
    return row

def generate_jobs(config):
    _, activities, recipes, locations, services, _, materials = load_all_game_data()
    from drop_calculator import DropCalculator
    drop_calc = DropCalculator()
    
    jobs = []
    for run in config['runs']:
        run_name = run['run_name']
        
        target_list = []
        for t in run['targets']:
            enum_val = OPTIMAZATION_TARGET[t['name']]
            target_list.append((enum_val, float(t['weight'])))

        # Process Activities
        for act in activities:
            locs = act.locations if act.locations else [None]
            
            # Extract Input Requirements for Activities (e.g., Baits vs Tools)
            input_reqs = [r for r in act.requirements if getattr(r.type, 'value', r.type) in ('keyword_count', 'input_keyword', 'item')]
            valid_input_combinations = [[]] # Default to empty input list
            
            if input_reqs:
                req_options = []
                for req in input_reqs:
                    req_type_val = getattr(req.type, 'value', req.type)
                    valid_mats = []
                    
                    if req_type_val in ('keyword_count', 'input_keyword') and req.target:
                        kw_target = req.target.lower().replace("_", " ").strip()
                        for mat in materials:
                            if hasattr(mat, 'keywords') and mat.keywords:
                                if kw_target in [k.lower().replace("_", " ").strip() for k in mat.keywords]:
                                    if is_material_level_valid(mat, req):
                                        valid_mats.append(mat.id)
                    elif req_type_val == 'item' and req.target:
                        item_target = req.target.lower()
                        for mat in materials:
                            if mat.id == item_target or mat.id == f"{item_target}_fine":
                                valid_mats.append(mat.id)
                    
                    # BUG FIX: If no materials satisfy this requirement, it is a TOOL requirement (Provided by Gear).
                    # We append [None] so itertools.product doesn't collapse the entire activity matrix.
                    if not valid_mats:
                        req_options.append([None])
                    else:
                        req_options.append(valid_mats)
                
                # Generate combinations, filtering out the 'None' placeholders (which gear will handle)
                raw_combinations = list(itertools.product(*req_options))
                valid_input_combinations = [
                    [mat_id for mat_id in combo if mat_id is not None]
                    for combo in raw_combinations
                ]
                
                # Deduplicate in case multiple requirements were gear-only
                valid_input_combinations = [list(x) for x in set(tuple(x) for x in valid_input_combinations)]

            for loc in locs:
                for input_combo in valid_input_combinations:
                    jobs.append({
                        "run_name": run_name, "targets": target_list, "type": "activity",
                        "id": act.id, "is_fine": False, "service_id": None, "location_id": loc,
                        "selected_inputs": list(input_combo)
                    })

        # Process Recipes
        for rec in recipes:
            can_be_fine = False
            if getattr(rec, 'materials', None):
                for mat_group in rec.materials:
                    if mat_group[0].item_id.replace("_fine", "") in drop_calc.fine_material_map:
                        can_be_fine = True
                        break

            if rec.service.lower() != "none":
                compat_services = get_compatible_services(rec, services)
                for srv in compat_services:
                    jobs.append({
                        "run_name": run_name, "targets": target_list, "type": "recipe",
                        "id": rec.id, "is_fine": False, "service_id": srv.id, "location_id": None
                    })
                    if can_be_fine:
                        jobs.append({
                            "run_name": run_name, "targets": target_list, "type": "recipe",
                            "id": rec.id, "is_fine": True, "service_id": srv.id, "location_id": None
                        })
            else:
                jobs.append({
                    "run_name": run_name, "targets": target_list, "type": "recipe",
                    "id": rec.id, "is_fine": False, "service_id": None, "location_id": None
                })
                if can_be_fine:
                    jobs.append({
                        "run_name": run_name, "targets": target_list, "type": "recipe",
                        "id": rec.id, "is_fine": True, "service_id": None, "location_id": None
                    })
                
    return jobs

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="WalkScape Gear Benchmark Tool")
    parser.add_argument("--config", default="brute_force_config.json", help="Path to JSON config file")
    args = parser.parse_args()

    with open(args.config, "r") as f:
        config = json.load(f)

    user_state_dict = {
        "user_ap": 0,
        "user_total_level": 0,
        "owned_item_counts": None,
        "owned_collectibles": [],
        "skill_levels": {},
        "skill_group_levels": {},
        "user_reputation": {},
        "owned_pets": {},
        "calculated_char_lvl": 99
    }
    
    if not config.get("use_theoretical_max", False) and "user_data_path" in config:
        print(f"Loading personal user data from: {config['user_data_path']}...")
        
        with open(config["user_data_path"], "r", encoding="utf-8") as f:
            raw_user_json = json.load(f)
            
        user_state_dict["owned_item_counts"] = extract_user_counts(raw_user_json)
        
        _, _, _, _, _, all_colls, _ = load_all_game_data()
        user_state_dict["owned_collectibles"] = get_user_collectibles(all_colls, raw_user_json)
        user_state_dict["user_ap"] = raw_user_json.get("achievement_points", 0)
        user_state_dict["user_reputation"] = extract_user_reputation(raw_user_json)
        user_state_dict["owned_pets"] = extract_user_pets(raw_user_json)
        
        steps = raw_user_json.get("steps", 0)
        user_state_dict["calculated_char_lvl"] = calculate_char_level_from_steps(steps)
        
        if "skills" in raw_user_json and isinstance(raw_user_json["skills"], dict):
            user_state_dict["user_total_level"] = calculate_total_level(raw_user_json["skills"])
            
            for s_name, s_xp in raw_user_json["skills"].items():
                s_name_clean = s_name.replace("Skill", "").lower()
                user_state_dict["skill_levels"][s_name_clean] = calculate_level_from_xp(s_xp)
                
            user_state_dict["skill_group_levels"] = {
                "gathering": sum(user_state_dict["skill_levels"].get(s, 0) for s in GATHERING_SKILLS),
                "artisan": sum(user_state_dict["skill_levels"].get(s, 0) for s in ARTISAN_SKILLS),
                "utility": sum(user_state_dict["skill_levels"].get(s, 0) for s in UTILITY_SKILLS)
            }
                
        print(f"Loaded {len(user_state_dict['owned_item_counts'])} items! AP: {user_state_dict['user_ap']} | Lvl: {user_state_dict['calculated_char_lvl']}")


    jobs = generate_jobs(config)
    
    # jobs = jobs[:5]
    # print(" ,".join([job["id"] for job in jobs]))
    print(f"Executing {len(jobs)} optimization permutations.")
    
    start_time = time.time()
    results = []

    with ProcessPoolExecutor(initializer=worker_init, initargs=(user_state_dict,)) as executor:
        progress_bar = tqdm(
            executor.map(process_job, jobs, chunksize=1), 
            total=len(jobs), 
            desc="Optimizing Gear",
            mininterval=0.5
        )
        
        for res in progress_bar:
            if res:
                results.append(res)

    if results:
        keys = results[0].keys()
        with open("benchmark_results.csv", "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=keys)
            writer.writeheader()
            writer.writerows(results)
            
        print(f"\nDone! Exported {len(results)} rows to benchmark_results.csv")
    else:
        print("\nNo valid results generated.")
        
    print(f"Total execution time: {round(time.time() - start_time, 2)} seconds")